services:
  postgres:
    container_name: code-reviewer-pg
    image: ankane/pgvector
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: code-reviewer-ai
      PGDATA: /data/postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
